os:
  - linux

language: perl

perl:
  - 5.30
  - 5.28
  - 5.26
  - 5.24
  - 5.22
  - 5.20
  - 5.18
  - 5.16
  - 5.14

script:
  prove -lrv t/

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers; source ~/travis-perl-helpers/init; build-perl; fi
  - perl -V
  - cpanm --notest Test::More~0.98
